### ISSUE TITLE
Problem information doesn't persist through OpenLab login (revisited)

### ISSUE THREAD

**Issue by jonasreitz** [livinglab/webwork-for-wordpress#21]
This is similar to, but not the same as, the prior issue:
https://github.com/livinglab/webwork-for-wordpress/issues/3 

Bree reported this (on the OpenLab site), and I'm getting the same behavior.  For the record, here is Bree's report:

> – I’m using OSX Yosemite / FF 47.
> – When I click on “Ask a question” in WeBWorK, I’m sent to this page: http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_da46388874cd0d0511adfa93af483680#/problem/ .
> – When I’m already logged in to my account it’s not an issue but if I have to log in, once I do so, I see the site title and nav but not the problem, and at the bottom of the page it says “Loading…”
> – Also, by log in, I mean log in to an OLdev user account to access the Webwork playground site, not log in to access dev

I'm seeing the same behavior, on OS 10.11.6 (El Capitan) in Chrome Version 52.0.2743.116 (64-bit) (but once again, only when I am not already logged in to the OpenLab).

Clicking "Ask for Help" on this page:

http://mathww.citytech.cuny.edu/webwork2/WW-Dev/1-RationalExpressions/7/

when not logged in, I get sent to this login page: 

http://openlabdev.org/wp-login.php?redirect_to=http%3A%2F%2Fopenlabdev.org%3Fwebwork%3D1%26webwork_user%26remote_class_url%3Dhttp%3A%2F%2Fmathww.citytech.cuny.edu%2Fwebwork2%2FWW-Dev%2F 

and, after logging in, to this page (which does not display the problem info, instead just the word "Loading..." in the part of the screen where the problem should be):

http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_0369bc1495d8ef1a98927eb572750baa#/problem/ 

Here's a screenshot:
![screen shot 2016-08-13 at 8 29 37 pm](https://cloud.githubusercontent.com/assets/17364219/17646373/2d3adc1a-6194-11e6-8aff-4c82cb49958e.png)

Alternatively, once I'm logged in to the OpenLab, if I click "Ask for Help" on the same  WW page, I get sent here (and the problem displays fine): 

http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_0369bc1495d8ef1a98927eb572750baa#/problem/Library/CollegeOfIdaho/setAlgebra_06_02_AddSubRationalExpressions/62IntAlg_23_AddSubRatExp.pg 

NOTE: This is different than the previous instance of this issue, documented here:
https://github.com/livinglab/webwork-for-wordpress/issues/3
in that it seems to occur whether or not I have already submitted a wrong answer to the WW problem - the only necessary condition seems to be "not logged in to the OpenLab".

- Jonas

**Comment by boonebgorges** [comment]
@jonasreitz Thanks to you (and to Bree) for the details. This should be fixed.

**Comment by bree-z** [comment]
@boonebgorges Thanks, Boone.  I'm still seeing the same behavior.  

I clicked on Ask for Help from this page: [http://mathww.citytech.cuny.edu/webwork2/WW-Dev/11-Circles/1/ ](http://mathww.citytech.cuny.edu/webwork2/WW-Dev/11-Circles/1/ )

I get this log in page: [http://openlabdev.org/wp-login.php?redirect_to=http%3A%2F%2Fopenlabdev.org%3Fwebwork%3D1%26webwork_user%3Dbzuckerman%26remote_class_url%3Dhttp%3A%2F%2Fmathww.citytech.cuny.edu%2Fwebwork2%2FWW-Dev%2F](http://openlabdev.org/wp-login.php?redirect_to=http%3A%2F%2Fopenlabdev.org%3Fwebwork%3D1%26webwork_user%3Dbzuckerman%26remote_class_url%3Dhttp%3A%2F%2Fmathww.citytech.cuny.edu%2Fwebwork2%2FWW-Dev%2F)

After logging in, I see this page, which just says "Loading...": [http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_6ea42170ed5c539b46c107f318710846#/problem/](http://openlabdev.org/webwork-playground/?post_data_key=webwork_post_data_6ea42170ed5c539b46c107f318710846#/problem/

**Comment by boonebgorges** [comment]
Thanks for the details, @bree-z. There was a remaining bug that only came up in certain circumstances on openlabdev.org. It should be fixed by d36acd2. Can you please try again?

**Comment by bree-z** [comment]
Thanks, Boone.  I don't have the same "Loading" text but now I don't see any WW problem.  From the same WW source URL as above, when I click on Ask for Help, I'm redirected to login here: [http://openlabdev.org/wp-login.php?redirect_to=http%3A%2F%2Fopenlabdev.org%2Fwebwork-playground%2F%3Fwebwork%3D1%26webwork_user%3Dbzuckerman%26remote_class_url%3Dhttp%3A%2F%2Fmathww.citytech.cuny.edu%2Fwebwork2%2FWW-Dev%2F](http://openlabdev.org/wp-login.php?redirect_to=http%3A%2F%2Fopenlabdev.org%2Fwebwork-playground%2F%3Fwebwork%3D1%26webwork_user%3Dbzuckerman%26remote_class_url%3Dhttp%3A%2F%2Fmathww.citytech.cuny.edu%2Fwebwork2%2FWW-Dev%2F)

After logging in I'm on this page, which doesn't have the WW problem: [http://openlabdev.org/webwork-playground/?webwork=1&webwork_user=bzuckerman&remote_class_url=http%3A%2F%2Fmathww.citytech.cuny.edu%2Fwebwork2%2FWW-Dev%2F](http://openlabdev.org/webwork-playground/?webwork=1&webwork_user=bzuckerman&remote_class_url=http%3A%2F%2Fmathww.citytech.cuny.edu%2Fwebwork2%2FWW-Dev%2F)

Here's a screenshot:

![8-16-2016 2-38-19 pm](https://cloud.githubusercontent.com/assets/7189824/17711476/d13f4602-63bf-11e6-9cc6-029f0e7d9fb6.png)

**Comment by boonebgorges** [comment]
What a nightmare. I've made another attempt to make this work properly. Could you please turn your eagle eye to it again? Thanks for your patience.

**Comment by bree-z** [comment]
Thanks, @boonebgorges . Looks good!

**Comment by boonebgorges** [comment]
Whoop!!
