### ISSUE TITLE
Question-level email subscription

### ISSUE THREAD

**Issue by boonebgorges** [livinglab/webwork-for-wordpress#70]
This may need design work if it's going to happen for the spring, since we may want to change the heart icon to something else (a bell, maybe).

**Comment by drdrew42** [comment]
It might be that we keep the "like" as is and stick something like a bell next to it for the 'subscribe' functionality? The number of subscribers may be ignored, or could be added to the 'popularity' rating for the question...

**Comment by boonebgorges** [comment]
Yes, I think that's the best way forward in the long run, but I think it's beyond what we can do for the spring.

**Comment by boonebgorges** [comment]
In https://www.dropbox.com/s/v1yosvl4yozxwal/OLWW_LAYOUT_PROBLEMPOSTV4-EDITQuestion.png?dl=0, subscriptions are mocked up as being per-question. I'll see what can be done to implement this for the Fall.

**Comment by boonebgorges** [comment]
This is up and ready to test on openlabdev.org.

Previously, question-author subscriptions had been hardcoded. Now that subscriptions are opt-in, I've written a script that subscribes authors to their own questions.

**Comment by drdrew42** [comment]
Initial experiment worked - I was emailed when I subscribed and then commented on a question. I then unsubscribed and commented again, and did not receive a notification. Awesome!

My only immediate observation is regarding placement of the notification button - it seems to be a little buried down there at the bottom of the thread. I guess it's only compounded by the fact that we've got some insanely long threads going... Regardless, feel free to ignore this for now - it's not a testing issue.

**Comment by moui72** [comment]
I'm seeing a rendering issue -- the action icons appear to be overlapping. Anyone else see this?

Windows 10 Home v1703 (64-bit) 
Chrome 59.0.3071.115 (Official Build) (64-bit)

![render-action-icons](https://user-images.githubusercontent.com/3885628/28690314-bac4b7fe-72e6-11e7-8efd-e7cade3e9318.png)

**Comment by boonebgorges** [comment]
@moui72 You shouldn't be seeing the subscription icon (the bell) on the main question index, but only on the single problem (zoomed-in) view. Can you confirm? Please be sure you've done a hard refresh, and if you're still seeing it, please share URLs.

**Comment by moui72** [comment]
The emails are sending!

I've noticed another potential issue, though. The E-mail I was sent including the following url linkback: 

> http://openlabdev.org/webwork-playground/#/problem/local/CoordinatePlaneTrig/ratio-inequality-xyr.pg/question-11392

however, this gave me an index view. the zoomed-in url for that question seems to be:

> http://openlabdev.org/webwork-playground/#:problemId=local/CoordinatePlaneTrig/ratio-inequality-xyr.pg:questionId=11392

the difference being `/#/problem/local/` vs `/#:problemId=local/`

**Comment by drdrew42** [comment]
I'm also seeing the overlapping bell whenever a question is collapsed.

http://openlabdev.org/webwork-playground/#:problemId=local/ShiftingParabolas/shift-down.pg:questionId=11373

<img width="690" alt="screen shot 2017-07-27 at 4 42 29 pm" src="https://user-images.githubusercontent.com/3912882/28691373-b1babdbc-72ea-11e7-973e-80748b3d05f6.png">

Safari 10.1.1 on MacOS 10.12.5

**Comment by boonebgorges** [comment]
Ah! Collapsing. Thanks. I assume we have to remove the icon for collapsed questions.

Incorrect links are due to changes #24.

I'll make these updates and report back.

**Comment by boonebgorges** [comment]
Overlapping icons and incorrect email links should be fixed on webwork-playground.

**Comment by moui72** [comment]
I'm still getting overlapping icons in the following context:

Logged out, zoomed in view, question expanded (not collapsed).

http://openlabdev.org/webwork-playground/#:problemId=local/setGeogebra/circle-center-multians-inc/circle-center-multians-inc.pg:questionId=11445


![screenshot_2017-08-08-11-13-49](https://user-imag
es.githubusercontent.com/3885628/29079457-33f9b41a-7c2b-11e7-8cfb-b420a435b1c6.jpg)

**Comment by moui72** [comment]
The subscription email now has the correct link. I will break the overlapping icons issue out into a new issue.
