### ISSUE TITLE
interpret linebreaks

### ISSUE THREAD

**Issue by moui72** [livinglab/webwork-for-wordpress#82]
when asking a question or making a reply, linebreaks are ignored outright

it might be nice to allow some for formatting purposes

**Comment by boonebgorges** [comment]
This should now be fixed.

**Comment by moui72** [comment]
No go. See http://openlabdev.org/webwork-playground/#:problemId=local/ShiftingParabolas/shift-down.pg:questionId=11370 and screenshot below

![image](https://user-images.githubusercontent.com/3885628/28588567-fca93482-7148-11e7-8d55-de4d73315207.png)

Entered text included many linebreaks in both fields at various intertextual places

Do I need to bust my cache harder? Here's the script my browser is loading (I assume this is the relevant one)

http://openlabdev.org/webwork-playground/wp-content/plugins/webwork/assets/js/webwork-scaffold.js?ver=4.8-1.7.11

**Comment by boonebgorges** [comment]
Can you please share the exact text that you have entered, along with info about your OS/browser? It's possible that the issue is linebreak encoding, for which I may need more generous regular expressions. https://github.com/livinglab/webwork-for-wordpress/commit/1bdf3d614456712ed8b4cce8a4dd8d0913e051fe

The application JS is not the file that you've linked, though if you are seeing other improvements then I assume that an old cache is not the issue. (The issue is on the server anyway.)

**Comment by moui72** [comment]
Tested on macOS 10.12.5 (Sierra) with Chrome 59.0.3071.115 (Official Build) (64-bit)

Text:

```
I am responding to this thing

with

linebreaks!
```

![image](https://user-images.githubusercontent.com/3885628/28588997-4aec8490-714a-11e7-877e-30a916a906cd.png)

The `¬` represents a new line character (`\n`)

![image](https://user-images.githubusercontent.com/3885628/28589077-8a6e4afe-714a-11e7-94a0-2835514cbbc0.png)

![image](https://user-images.githubusercontent.com/3885628/28589040-6ec9a12c-714a-11e7-81d4-1e61219d6add.png)

**Comment by moui72** [comment]
I just updated chrome to `60.0.3112.78 (Official Build) (64-bit)` with no change in behavior

**Comment by boonebgorges** [comment]
Thank you for the details. Like so many other parts of this application, there are about a hundred text encoding steps that happen between WW and the server and WP and the browser. I've just put something in place on webwork-playground that addresses this specific post - can you play with it a bit and see if it matches what you'd expect?

**Comment by moui72** [comment]
seems to be working in the ask a question and the reply field, but not in the "what i've tried" field

text entered in all three fields
```
I am responding to this thing

with

linebreaks!
```

result
![linebreaks-what-ive-tried](https://user-images.githubusercontent.com/3885628/28691123-c3f3a38c-72e9-11e7-837a-99c9499ee84f.png)

**Comment by boonebgorges** [comment]
Whoops, I missed `tried`. This should now be resolved.

**Comment by moui72** [comment]
the `tried` issue is still working, but I think it's display only: when I edit a question with linebreaks in the `tried` field, they are still there. notably, the question field will have `\n` stripped out and replaced by `<br />` but `tried` still has `\n`

also, i wonder if it is worth the effort to reverse the effect for editing, so that users see line breaks instead of `<br />` ?

i can post screenshots later on, right now i dont have time sorry

**Comment by moui72** [comment]
A few corrections to the above: if I edit a question/reply immediately after posting it, the `\n` characters are not replaced by `<br />` but after a page refresh, they are.

`tried` always has `\n` (they are no longer stripped out) but never displays as line break or `<br />`

## Demonstrating `tried` behavior
Display
![webwork playground just another city tech openlab site 1](https://user-images.githubusercontent.com/3885628/29089644-eaa2055e-7c4a-11e7-9072-8e5c3984c543.png)

Immediate edit and edit after reload
![webwork playground just another city tech openlab site 4](https://user-images.githubusercontent.com/3885628/29089843-b5cd44aa-7c4b-11e7-8b8c-dcc620b229c4.png)

## Demonstrating question/reply behavior with page refresh
Display
![webwork playground just another city tech openlab site 5](https://user-images.githubusercontent.com/3885628/29089910-e73f8a7a-7c4b-11e7-9fbc-7fd6c72209bc.png)

Immediate edit
![webwork playground just another city tech openlab site 3](https://user-images.githubusercontent.com/3885628/29089757-54a8bbb4-7c4b-11e7-9de8-1e5bf188e7b6.png)

Edit after reload
![webwork playground just another city tech openlab site](https://user-images.githubusercontent.com/3885628/29089643-ea9f346e-7c4a-11e7-83e3-9b581d47e1c1.png)

**Comment by boonebgorges** [comment]
This issue is truly awful. I've done some work to try addressing the various problems:

* System linebreaks (of the `\r` `\n` variety) are now left unprocessed by the server; previously, I'd been converting them to `<br />` in some cases, which was causing the Edit problems
* The same routines for converting linebreaks in question/response text are also applied to problem text. However, problem text has a couple of oddities associated with it, including line breaks inside of HTML text (either due to being entered that way in WW, or some quirk of WW's POST mechanism). I'm doing my best to clean this up when the problem text is received from WW.

One side-effect is that text for some problems now appears to have more linebreaks than previously. See eg http://openlabdev.org/webwork-playground/#:problemId=local/CoordinatePlaneTrig/six-trig-point-q1.pg:questionId=11454. In truth, this is a *more accurate* representation of the markup as it's received from WW, though it does take up more vertical space than it seems like it ought to. I don't think there's much more we can do to "fix" this without retooling the WW-WP connection.

**Comment by moui72** [comment]
it's looking good now, sorry it's such a pain =\ I appreciate your commit message for 075442b 😆

**Comment by moui72** [comment]
@bree-z would you have a minute to verify that there are no lingering issues?

**Comment by bree-z** [comment]
@moui72 yep, also on the list for tomorrow.

**Comment by bree-z** [comment]
This looks OK to me in Firefox, but not Chrome.  Linebreaks appear in Firefox for both questions and replies.  In Chrome they don't appear for either.  I'm using OSX 10.12.5, Firefox 54 and Chrome 60.0.3112.90.

See, for example:

http://openlabdev.org/webwork-playground/#:problemId=local/CoordinatePlaneTrig/six-trig-point-q1.pg:questionId=11468

### In Chrome

![linebreaks_askquestionchrome](https://user-images.githubusercontent.com/7189824/29228926-ce5edbf4-7ea9-11e7-9003-ce8e7a1248f4.png)

**After submitting:**

![linebreaks_questionresponse_chrome](https://user-images.githubusercontent.com/7189824/29228941-e1d37618-7ea9-11e7-8cda-81c74da7837c.png)


### Same question in Firefox:

![linebreaks_firefox](https://user-images.githubusercontent.com/7189824/29228886-a1910c82-7ea9-11e7-8962-a6e251bd1c00.png)

**Comment by boonebgorges** [comment]
@bree-z  Thanks for the screenshots. It's looking OK to me, though I'm not near a Mac to check if that's the issue. Could you please triple-check that your cache is clean? shift-refresh

**Comment by bree-z** [comment]
So sorry @boonebgorges !  I thought I'd cleared my cache, but maybe that was Firefox...or something else. (Too many browsers and windows and tabs for one week.)

It looks good now!  I think we can close this.

**Comment by boonebgorges** [comment]
Phew - I did not want to think about this issue anymore :-D

**Comment by bree-z** [comment]
This looked like a rough one!

**Comment by moui72** [comment]
Yay! Thanks Bree
